emporium:
  host: emporium.bigboxapp.com
  nameSpace: bigboxapp-production
  secretName: letsencrypt-nginx
  image:
    repository: registry.digitalocean.com/sg-bigboxapp-cr1/emporium
    tag: "0.0.2"
  replicaCount: 3